Add basic fork workflow functionality
BetaHuhn/repo-file-sync-action pull request #135
Opened 2021-11-20 00:01 UTC by xanjohns

Adds the option of a "fork and pull request" workflow.

Can be enabled by specifying which user/bot account contains the forks, using the `FORK` input, defaulted to false.

- Changes to the cloned repository are pushed to the fork, instead of back upstream
- Pull requests `head` is changed to the new branch on the forked repository

The advantage of this style is no write access is required to upstream repositories. This also means, however, that adding labels/assignees is not possible, so that has to be disabled if `FORK` is specified.

Note: This setup assumes the forks have already been created.

2021-11-23 22:03 UTC, xanjohns commented
After having though about it a little more, I think it would make the most sense to include the step of actually forking repositories in this action as well, since we have already parsed the file containing the list of external repositories we are working with. I've added another commit to include the few lines needed to fork.

2021-11-28 13:33 UTC, BetaHuhn commented
> After having though about it a little more, I think it would make the most sense to include the step of actually forking repositories in this action as well

Yeah, makes sense.

Still marked as a draft, is it ready to review?

2021-12-02 15:14 UTC, xanjohns commented
Apologies for the slow response, but yes!

2021-12-04 15:42 UTC, BetaHuhn requested changes

2021-12-04 15:42 UTC, BetaHuhn commented on src/config.js
> +			key: 'FORK'
Please add a default value, in our case `false`.

You can also set the `FORK` option to `disableable` ([more info](https://github.com/BetaHuhn/action-input-parser#all-options)).

```suggestion
			key: 'FORK',
			default: false,
			disableable: true
```

2021-12-04 16:00 UTC, BetaHuhn commented
Other than the small change, everything looks good to me.

Could you add the `FORK` input to the end of the [Action Inputs table](https://github.com/BetaHuhn/repo-file-sync-action#%EF%B8%8F-action-inputs) and add an example on how to use it to the [examples section](https://github.com/BetaHuhn/repo-file-sync-action#-examples) in the README?

Will merge it after that.

2021-12-04 16:01 UTC, BetaHuhn approved these changes

2021-12-11 03:58 UTC, xanjohns commented
I've added `FORK` to the Action Inputs table and provided an example/description.

2021-12-11 13:02 UTC, merged

2021-12-11 13:03 UTC, BetaHuhn commented
Thanks!