Fix to let branch can contain slash
BetaHuhn/repo-file-sync-action pull request #57
Opened 2021-06-10 13:27 UTC by adaam

I meet a problem when I use this script to sync files with branch name with slash.
I think it does not need to split with slash when parsing branch.
But I'm not a javascript expert, just found it will work when branch name with slash.
Please help to review if it makes sense.

2021-06-10 17:18 UTC, BetaHuhn requested changes

2021-06-10 17:18 UTC, BetaHuhn commented on src/config.js
> +}
Please remove this newline at the end.

2021-06-10 17:18 UTC, BetaHuhn commented
Hey @adaam,

Thanks for taking the time to create this PR! Syncing a branch with a `/` is totally a valid use case which I oversaw when writing the code. 

If you could remove the added newline at the end, I will merge it!

2021-06-11 02:28 UTC, adaam commented on src/config.js
> +}
Sure. Newline removed.

2021-06-11 02:30 UTC, adaam commented
Newline in two files are removed.

2021-06-11 09:30 UTC, merged

2021-06-11 09:37 UTC, BetaHuhn commented
Thanks!